require "user.keymaps"
require "user.options"
require "user.plugins"
require "user.colorscheme"
require "user.which-key"
require "user.telescope"
require "user.nvim-colorizer"
require "user.nvim-cmp"
require "user.lsp"
require "user.treesitter"
require "user.autopairs"
require "user.gitsigns"
require "user.nvimtree"
require "user.todo-comments"
require "user.lualine"
require "user.bufferline"
require "user.startify"
require "user.vimtex"
require "user.chatgpt"
require "user.null-ls"
require "user.toggleterm"
require "user.tmux-navigation"
-- require "user.orgmode"
require "user.neorg"
-- require "user.dashboard"
